ignore:
  - "extern/cxxopts/**/*"
  - "extern/taskflow/**/*"
  - "extern/qfr/apps/*"
  - "extern/qfr/test/*.cpp"
  - "extern/qfr/mqt/*"
  - "extern/qfr/extern/json/**/*"
  - "extern/qfr/extern/pybind11/**/*"
  - "extern/qfr/extern/pybind11_json/**/*"
  - "extern/qfr/extern/zx/**/*"
  - "extern/qfr/extern/dd_package/extern/**/*"
  - "extern/qfr/extern/dd_package/test/*.cpp"
  - "apps/*"
  - "test/*.cpp"
  - "mqt/**/*"

coverage:
  range: 60..95
  precision: 1
  status:
    project:
      default:
        threshold: 0.5%
    patch:
      default:
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
