name: cpp-linter

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  clang-version: 16

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install clang-${{ env.clang-version }}
        run: |
          sudo apt-get --quiet update
          wget https://apt.llvm.org/llvm.sh -O ${{ runner.temp }}/llvm_install.sh
          chmod +x ${{ runner.temp }}/llvm_install.sh
          if sudo ${{ runner.temp }}/llvm_install.sh ${{ env.clang-version }}; then
            sudo apt-get install -y clang-format-${{ env.clang-version }} clang-tidy-${{ env.clang-version }} || exit 1
          else
            echo "Installation from script failed."
            exit 1
          fi
          echo "CC=clang-${{ env.clang-version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ env.clang-version }}" >> $GITHUB_ENV
      - name: Install OpenCV
        run: |
          sudo apt-get install --no-install-recommends libopencv-dev
      - name: Generate compilation database
        run: |
          echo $CC
          echo $CXX
          $CC --version
          $CXX --version
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DBINDINGS=ON -DBUILD_DDSIM_TESTS=ON
      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ""
          tidy-checks: ""
          version: ${{ env.clang-version }}
          thread-comments: true
          step-summary: true
          database: "build"
          extra-args: -std=c++17
          files-changed-only: true
      - name: Fail if linter found errors
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Linter found errors" && exit 1
